### ISSUE TITLE
Anthurium missing particle(?) texture when broken.

### ISSUE THREAD

**Issue by Chalpl** [Chalkboard-Mods/floral-flair-fabric#1]
When you break/mine the Anthurium flower, there is no texture for the particles that get emitted when it breaks, leaving it bulky black and purple boxes. 

Version 1.2.0 on MC 1.18.1 with Fabric 0.13.3. Fabric API Version: 0.46.6. Cloth Config API | 6.2.57.

**Comment by Ibex80** [comment]
Fixed.
